name: torf
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - pip
  - numpy
  - cudatoolkit=11.3
  - pip:
    - configargparse
    - h5py
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - openexr
    - pillow
    - scipy
    - tensorflow-gpu==2.5.0
    - tensorflow-graphics==2020.5.20
    - tensorflow_addons
    - tqdm
